- hosts: localhost
  become: true

  vars:
    token: "783bde.3f89s0fje9f38fhf"
    # The follow two parameter was explained here https://github.com/geerlingguy/ansible-role-kubernetes#variables-to-configure-kubeadm-and-kubelet-through-command-line-options
    kubernetes_pod_network:
      cni: 'flannel'
      cidr: '10.244.0.0/16'
    kubernetes_yum_gpg_check: false
    kubernetes_yum_repo_gpg_check: false
    kubernetes_config_kubelet_configuration:
      cgroupDriver: "systemd"
      failSwapOn: false
    kubernetes_config_init_configuration:
      # details of these parameters could be found here https://pkg.go.dev/k8s.io/kubernetes/cmd/kubeadm/app/apis/kubeadm/v1beta1
      localAPIEndpoint:
        advertiseAddress: "{{ kubernetes_apiserver_advertise_address | default(ansible_default_ipv4.address, true) }}"
      bootstrapTokens:
        - token: "{{ token }}"
          description: "another bootstrap token"
          usages:
          - authentication
          - signing
          groups:
          - system:bootstrappers:kubeadm:default-node-token
    kubernetes_allow_pods_on_master: true
  pre_tasks:
  - name: update all packages
    yum:
      name: '*'
      update_only: yes
      update_cache: yes
      state: latest

  - name: Install epel release
    yum:
      name: epel-release
      state: installed
      
  - name: Enable br_netfilter module
    modprobe:
      name: br_netfilter
      state: present
    when: >
      ansible_distribution != 'Debian' 
 
  roles:
    - role: geerlingguy.pip
    - role: geerlingguy.containerd
    - role: geerlingguy.kubernetes
